name: CI

on:
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4

      - run: |
          TAG="$(git describe --tags --abbrev=0 || echo v0.0.0)-dev-$(git rev-parse --short HEAD)"
          yarn nx-cloud record -- yarn nx run-many --target=release --parallel=3 --args="--version=$TAG"
