name: Branch Release

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    permissions:
      actions: read
      contents: read
      attestations: write # to provide attestations about built images (not implemented, but it could be nice)
      packages: write # to push the built docker images
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: 'ghcr.io'
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4

      - run: |
          TAG="$(git describe --tags --abbrev=0 || echo v0.0.0)-dev-$(git rev-parse --short HEAD)"
          yarn nx-cloud record -- yarn nx run-many --target=release --parallel=3 --args="--version=$TAG"
